name: Rust Example
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Rust benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Output Run Attempt
        run: echo ${{ github.run_attempt }}

      
      - name: ${{github.event.inputs.id}}
        run: echo run identifier ${{ inputs.id }}
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: test

      # - name: Get Current Job Log URL
      #   uses: Tiryoh/gha-jobid-action@v0
      #   id: jobs
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     job_name: ${{ github.job }}

      
      # - run: rustup toolchain update nightly && rustup default nightly
      # - name: Run benchmark
      #   run: cargo +nightly bench | tee output.txt
      