name: Rust Example
on:
  push:
    branches:
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run Rust benchmark example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: test
      # - run: rustup toolchain update nightly && rustup default nightly
      # - name: Run benchmark
      #   run: cargo +nightly bench | tee output.txt
      